### ISSUE TITLE
Inference step

### ISSUE THREAD

**Issue by cuishuhao** [martyn/safetensors-merge-supermario#1]
Hello, 
thanks for sharing!
I wonder how you get the merged image? Inference for only One step or 50steps? It will be better to provide the prompt and seed!
Thanks

**Comment by martyn** [comment]
Thanks! The linked json has the exact ComfyUI settings but the steps were set to 10 for all the images using the SDTurboScheduler. Single step doesn't work on the merged model. I didn't try to tune the lambda or p values to improve it.
