### ISSUE TITLE
SD Turbo (SD 2.1) vs SDXL Turbo merging?

### ISSUE THREAD

**Issue by cian0** [martyn/safetensors-merge-supermario#2]
Is it possible to merge SD 2.1 models with SD Turbo model? Streamdiffusion only supports SD 2.1 hence I wanted to know if it's possible, thanks!

**Comment by martyn** [comment]
I haven't gotten good results from 2.1. The merge seems to perform worse than the base models. I tried merging with p=0.2 and lambda=0.5.
