### ISSUE TITLE
Which merge.py corresponds to the merge method of DARE?

### ISSUE THREAD

**Issue by guanfaqian** [martyn/safetensors-merge-supermario#4]
Thanks for sharing!

hf_merge.py？ merge.py？

Which merge.py corresponds to the merge method of DARE? 

I tried your merge.py following the default parameters -p 0.13 -lambda 3.0 but it doesn't work well. What exactly do these two parameters mean? Is there any connection?

**Comment by martyn** [comment]
Hi, https://github.com/martyn/safetensors-merge-supermario/blob/main/merge.py#L9 is the main merge method used by both files.
Lambda of 3.0 might be large.
P is percentage of weights to merge, it gets amplified as well. These variables are from the whitepaper https://arxiv.org/pdf/2311.03099.pdf 
I've found that 0.24 and 2.0 are good values to start with but it depends on the model and some experimentation is needed.
